language: node_js
install:
- npm i
before_install:
- wget https://releases.hashicorp.com/terraform/"$TF_VERSION"/terraform_"$TF_VERSION"_linux_amd64.zip
- unzip terraform_"$TF_VERSION"_linux_amd64.zip
- sudo mv terraform /usr/local/bin/
- rm terraform_"$TF_VERSION"_linux_amd64.zip
jobs:
  include:
  - stage: test
    script: npm test
  - stage: deploy qa
    if: type IN (push) and branch = qa
    env:
    - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_QA
    - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_QA
    script:
    - terraform -chdir=provisioning/qa init -input=false
    - echo "Deploying to qa"
    - terraform -chdir=provisioning/qa apply -auto-approve -input=false
  - stage: deploy production
    if: type IN (push) and branch = production
    env:
    - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_PRODUCTION
    - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_PRODUCTION
    script:
    - terraform -chdir=provisioning/production init -input=false
    - echo "Deploying to production"
    - terraform -chdir=provisioning/production apply -auto-approve -input=false
env:
  global:
  - TF_VERSION=1.0.11
  - secure: TWXvmnn9+683dFupAVoH9YKtj3AttCayIvPtUs075zN7pa+t/+1tDYPLrSzUk/Iy4TmsmOw2PJ4juuP3F7Nv+wqfkN2yij3p3IAZ2CNk2FsEdADGptn8Z2unvwS9k1kivTBPNR1/x6PruZdPC5t/209gd+oIlUEd728JyU7dtkWqftcZeUBGJXKbN/1igZ0NZgC+9BVomSBGe9fzJal+tzG+mVfBlDaXllBTFUz6ZpOWSx0Ixy4ydFZT06z/pM0AUWA163MExL8jAakZJuiWlAT8x7JM8fv6d0RfgxZuFzK0fMp6HEpiVipI6Kqj1bNs75/w1OxEuhcdJET6SIufcMhgPl1R2lMJMy4X0L2/f7r2hzVnPK1zNBIX/MOp2l4Qm+OpK1DtHTke963oKcI6cHTlQxgtsV30V+UZ3wjlMQG06ho61FoeKFAHpoXi5THvogheS4+Q1U6AgTv/qEu6AxAvyK6tZxvmU0hdTH5VaQhwnewNQDBqP0hXmIj1zv+hbrn0Ab2VyLRO7usVwTeZ3gzmP+ydj59CaWkKZIIzwFjbGKy5u1jaWr5uzM00k6Ge0K6DmGZj+c2/2rMRziG8pjCEV0VusY9ny5cZmjMFarzgTDcPMBiWj/nESDQScU+nMxxWxuRZJ7C/Mh2OqNBZUhuEs3pRrVLx8p6F6Blksbg=
