language: node_js
install:
- npm i
before_install:
- wget https://releases.hashicorp.com/terraform/"$TF_VERSION"/terraform_"$TF_VERSION"_linux_amd64.zip
- unzip terraform_"$TF_VERSION"_linux_amd64.zip
- sudo mv terraform /usr/local/bin/
- rm terraform_"$TF_VERSION"_linux_amd64.zip
jobs:
  include:
  - stage: test
    script: npm test
  - stage: deploy qa
    if: type IN (push) and branch = qa
    env:
    - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_QA
    - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_QA
    script:
    - terraform -chdir=provisioning/qa init -input=false
    - echo "Deploying to qa"
    - terraform -chdir=provisioning/qa apply -auto-approve -input=false
  - stage: deploy production
    if: type IN (push) and branch = production
    env:
    - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_PRODUCTION
    - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_PRODUCTION
    script:
    - terraform -chdir=provisioning/production init -input=false
    - echo "Deploying to production"
    - terraform -chdir=provisioning/production apply -auto-approve -input=false
env:
  global:
  - secure: L2r6tUkbOm4j3JtLjB43te1udbY2bZ48fpfyrhCXcJHEQ3beutZphxx4Zl/0r5lQXSYWJskYwvvuFAP0b5ywQRGzsY897BJKHqk4KXElbUVe/OubZ3QdZ8cSye/CzkFk+0h+d5vMVtVBbmKko8AaZgypYLgH0hC1aWsXUU1mHrXJRvlU6YdQXAJKJ1x+hiwpmvq6VvHuH2UMxnAKmQmFRyLsFJvAaLdV0LbJpa8anRgQS4ZncEVDqTXw9p93dmn1eBgcKir3YO7ceFfgE5dKq8OTZab1mCzBE04Z207VOBlr1uoeRJzSeBw3p3kPj2fn7Nj5AljUrfedHODNaoXKgtT/PoTLcuZYt8hIHnW12H9IJmSTyMkC769Qtff+LIKnuO2aBMdyo8hqK0AaLWaSWwcDSYUJ1GOd3gMUNEUFG14yLKZX2uDHrl9zg0qnZTz58Zpi1mCnrXscjCtKQwZ40kVoh0yDEWqC2X2+aHMC646DxSF16v8QL0jfZVcyozZJ3piY9lKgg/7062tXzAgyyISOL1S3/NmBNnxp1D77wY+C82pA/rZE4gEF4vMAb3sMw8yh8WDPIjZseCZB8iCOxl2uDLIaG8Ic5Lm/LqYHXxtJiV7izy7nMRoHk/C3gZXC8uq2q7YPCElgaAyCXegRrt5ZNBG+iTIM261dIqxDr1k=
  - TF_VERSION=1.0.11
