AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'firehose-avro-to-json-transformer'

Resources:
  AvroToJsonTransformer:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: lambda_function.lambda_handler
      Runtime: python3.12
      Timeout: 10
      Environment:
        Variables:
          NYPL_DATA_API_BASE_URL: https://qa-platform.nypl.org/api/v0.1/
          LOG_LEVEL: debug
